engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  rubocop:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true

ratings:
  paths:
  - Gemfile.lock
  - "**.rb"

exclude_paths:
- spec/**/*
